Fix KVM reboot after installation is finished
The reboot() method for KVM in tessia-baselib expects the domain to be
running, therefore, do not power off the domain before initiating
the reboot.

This fixes the following problem when installing a Fedora on a KVM domain:

20:11:28,776 DBG ui.gui.spokes.installation_progress: The installation has finished.
2021-02-08 19:11:30 | DEBUG | client.py(558) | closing connection
2021-02-08 19:11:30 | INFO | sm_base.py(723) | new state: target_reboot
2021-02-08 19:11:30 | INFO | plat_kvm.py(455) | rebooting the system now
2021-02-08 19:11:30 | DEBUG | client.py(481) | login: hostname='***' port='22' user='root' priv_key='None' timeout='10'
2021-02-08 19:11:30 | DEBUG | client.py(610) | open_shell: chroot_dir='None' shell_path='None'
2021-02-08 19:11:30 | DEBUG | client.py(630) | calling get_transport.open_session()
2021-02-08 19:11:30 | DEBUG | client.py(641) | calling channel.get_pty()
2021-02-08 19:11:30 | DEBUG | client.py(654) | calling channel.exec_command()
2021-02-08 19:11:31 | DEBUG | client.py(558) | closing connection
2021-02-08 19:11:31 | DEBUG | client.py(481) | login: hostname='***' port='22' user='root' priv_key='None' timeout='10'
2021-02-08 19:11:31 | DEBUG | client.py(610) | open_shell: chroot_dir='None' shell_path='None'
2021-02-08 19:11:31 | DEBUG | client.py(630) | calling get_transport.open_session()
2021-02-08 19:11:32 | DEBUG | client.py(641) | calling channel.get_pty()
2021-02-08 19:11:32 | DEBUG | client.py(654) | calling channel.exec_command()
2021-02-08 19:11:37 | DEBUG | client.py(558) | closing connection
2021-02-08 19:11:37 | DEBUG | kvm.py(226) | performing REBOOT HypervisorKVM: guest_name=*** parameters=None
2021-02-08 19:11:37 | DEBUG | wrapper.py(317) | state machine finished with ret_code=-3
2021-02-08 19:11:37 | DEBUG | wrapper.py(349) | preparing cleanup
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tessia/server/scheduler/wrapper.py", line 306, in start
    ret_code = self._machine.start()
  File "/usr/local/lib/python3.6/dist-packages/tessia/server/state_machines/autoinstall/machine.py", line 358, in start
    ret_val = self._machine.start()
  File "/usr/local/lib/python3.6/dist-packages/tessia/server/state_machines/autoinstall/sm_base.py", line 724, in start
    self.target_reboot()
  File "/usr/local/lib/python3.6/dist-packages/tessia/server/state_machines/autoinstall/sm_base.py", line 691, in target_reboot
    self._platform.reboot(self._profile)
  File "/usr/local/lib/python3.6/dist-packages/tessia/server/state_machines/autoinstall/plat_kvm.py", line 504, in reboot
    self._hyp_obj.reboot(system_profile.system_rel.name, None)
  File "/usr/local/lib/python3.6/dist-packages/tessia/baselib/common/params_validators/utils.py", line 91, in validate
    return func(*params)
  File "/usr/local/lib/python3.6/dist-packages/tessia/baselib/hypervisors/kvm/kvm.py", line 234, in reboot
    "running".format(guest_name))
RuntimeError: Domain *** is not running
2021-02-08 19:11:38 | DEBUG | kvm.py(71) | create HypervisorKvm: name='***' host_name='***' user='root' parameters='{}'
2021-02-08 19:11:38 | DEBUG | kvm.py(111) | performing LOGIN HypervisorKvm: name='***' host_name='***' user='root' parameters='{}'
2021-02-08 19:11:38 | DEBUG | linux.py(88) | create GuestLinux: name='***' host_name='***' user='root' extensions='{}'
2021-02-08 19:11:38 | DEBUG | client.py(481) | login: hostname='***' port='22' user='root' priv_key='None' timeout='60'
2021-02-08 19:11:43 | DEBUG | client.py(610) | open_shell: chroot_dir='None' shell_path='None'
2021-02-08 19:11:43 | DEBUG | client.py(630) | calling get_transport.open_session()
2021-02-08 19:11:43 | DEBUG | client.py(641) | calling channel.get_pty()
2021-02-08 19:11:43 | DEBUG | client.py(654) | calling channel.exec_command()
2021-02-08 19:11:44 | DEBUG | linux.py(208) | create distro system_name='***' _distro_obj='DistroGeneric'
2021-02-08 19:11:44 | DEBUG | client.py(610) | open_shell: chroot_dir='None' shell_path='None'
2021-02-08 19:11:44 | DEBUG | client.py(630) | calling get_transport.open_session()
2021-02-08 19:11:44 | DEBUG | client.py(641) | calling channel.get_pty()
2021-02-08 19:11:44 | DEBUG | client.py(654) | calling channel.exec_command()
2021-02-08 19:11:44 | INFO | plat_kvm.py(252) | Applying user-defined libvirt xml for volume ***
2021-02-08 19:11:44 | INFO | machine.py(256) | AutoInstall cleanup is running
Error: Job #116499 ended in FAILED state

Fixes: 3045583 ("Add support for autoinstall of Ubuntu 18")
Signed-off-by: Alexander Egorenkov <Alexander.Egorenkov@ibm.com>